services:
  js-app:
    build:
      context: .
    container_name: js-app
    restart: unless-stopped
    init: true
    # env_file: ./.env  # Uncomment if .env file exists
    ports:
      - "3000:3000"  # Exposed by Dockerfile, default app port
    # Add depends_on here if you add external services (e.g., database)
    # networks: [appnet]  # Uncomment if you add more services/networks

# No external services (databases, caches, etc.) detected in the project structure or Dockerfile.
# If your app requires a database or other services, add them below and update depends_on/networks accordingly.

# No volumes section needed as there are no persistent data services.

# networks:
#   appnet:
#     driver: bridge
